/// Defines the severity or category of a system notification.
enum NotificationType {
  /// General information.
  info,

  /// Warning about a potential issue (e.g., low stock).
  warning,

  /// Success message for a completed process.
  success,

  /// Critical error or failure.
  error,

  /// Message generated by the AI assistant.
  ai,
}
